### ISSUE TITLE
use_state_machine should be static

### ISSUE THREAD

**Issue by emmdie** [wyvernbw/wisp#2]
Sorry if I am missunderstanding something here, but I feel like the function use_state_machine() should be static, as you use it to create the state machine in the first place. Of course it is possible to circumvent this, by directly calling StateMachine.create() directly. 
Doing so without adjusting it, gives me an error: 
"Cannot call non-static function "use_state_machine()" on the class "Wisp" directly. Make an instance instead."   
Do note, that I am on Godot Version 4

**Comment by emmdie** [comment]
#3

**Comment by wyvernbw** [comment]
reopening this issue because it is relevant for godot 4, will add a godot 4 branch soon
